### ISSUE TITLE
can not use for 4k video

### ISSUE THREAD

**Issue by javacty** [satishsampath/frame-server#42] opened 2018-02-06 12:01 UTC
can not use for 4k video

**Comment by satishsampath** [comment] 2019-06-23 22:58
Can you give more details - which video editor application, project settings and steps to reproduce?

**Comment by javacty** [comment] 2019-06-24 03:43
adobe premiere cc 2018，adobe media encoder cc 2018
all step not report error，but result video file   have not picture when playing.

**Comment by satishsampath** [comment] 2019-07-28 18:48
Is the source video in 4k or the output via Frameserver in 4k? May be a few screenshots or a video showing the error will be useful

**Comment by satishsampath** [comment] 2019-08-04 15:04
Can you check if you have the older versions of frameserver plugin? @videocorr found that was the reason for issue #48 and fixed it. May be you have the same issue?

**Comment by videocorr** [comment] 2019-08-04 15:59
Most likely the problem is in something else, I have a video resolution of 4096x2160 render without problems

**Comment by satishsampath** [comment] 2019-09-07 15:06
Closing as I can't reproduce and other people are able to use successfully too. If you encounter this again, please reopen the issue and add steps or a video showing how it happens.

**Closed by satishsampath** 2019-09-07 15:06 UTC
