### ISSUE TITLE
Update Debugmode Frameserver for Adobe Premiere CC

### ISSUE THREAD

**Issue by albino1** [satishsampath/frame-server#37] opened 2015-07-28 23:17 UTC
**What is it:** Debugmode Frameserver is a plugin that acts as an intermediary between Adobe Premiere and other programs.  Basically it allows the user to pass video files to third party encoders.

**Where is it at now:** The last update to Frameserver was [2.14](http://www.debugmode.com/frameserver/) which added support for Adobe Premiere CS6.  

**What needs to be fixed:** With the release of Adobe Premiere CC, Frameserver is able to run once, after which it fails to load.  More importantly, Adobe Media Encoder appears to crash when launching and [you may need to uninstall Frameserver](https://github.com/satishsampath/frame-server/issues/25) to recover AME.  Since it seems to work the first time it would appear that the basic functionality of Frameserver is still intact, though what happens next to cause it to fail is unknown.

**Bug Bounty Goal:** Improve the stability of Frameserver in Adobe Premiere CC to the point where you can render multiple files and close/re-open AME without incident.

**Comment by albino1** [comment] 2015-07-28 23:20
I went ahead and created a Bug Bounty for this project which you can find here:

https://www.bountysource.com/issues/25095447-improve-stability-of-debugmode-frameserver-with-adobe-premiere-cc

**Comment by jonno85uk** [comment] 2015-09-29 20:22
It is possible to do multiple session rendering with the plugin, however, it is a pain:

1. After the 1st export close Premiere CC. 
2. Remove the debugmode plugins from "Plugins/Common". 
3. Restart Premiere and try to export any sequence. You don't actually have to export anything. Just get the AME window to appear. 
4. Close down Premiere, 
5. Put the plugins back. 

Debugmode will then work again for another, single use.

**Comment by albino1** [comment] 2015-09-30 05:01
Thanks for the workflow @jonno85uk, even if it's cumbersome I still appreciate it.

**Comment by wangqr** [comment] 2019-01-12 06:41
I have found that the plugin does not load on PrPro CC 2019 and made some small fixes to let it work (see https://github.com/satishsampath/frame-server/issues/43#issuecomment-453723267).
With this build, I can export multiple times and save the project without problem, using the "Export" option in the Export dialog.

I don't have AME installed so I am not sure if "Queue" is working properly, and not able to reproduce the AME issue. I'll test the AME issue later if I have time.

**Comment by satishsampath** [comment] 2019-06-23 22:55
This issue is fixed with the release of Frameserver 3.0 today. Get it at https://www.debugmode.com/frameserver/

**Closed by satishsampath** 2019-06-23 22:55 UTC
