### ISSUE TITLE
Does anyone want to start a Bug Bounty for this project?

### ISSUE THREAD

**Issue by albino1** [satishsampath/frame-server#36] opened 2015-07-26 08:44 UTC
Frame Server is a great tool, but unfortunately, as software like Premiere and Vegas has upgraded, it hasn't transitioned as well.  Does anybody want to go to [Bounty Source](https://www.bountysource.com/) and start a Bug Bounty to get it at least functioning in Premiere CC?  I'm willing to throw some money at it, but I'm not a developer and I wouldn't have the faintest idea how to create the bounty and meet the technical requirements necessary to explain what bug exactly needs fixing.  Unfortunately, "it's broke, somebody please fix it" isn't quite enough.

If somebody wants to start it up though, I'd gladly pitch in financially.

**Comment by satishsampath** [comment] 2015-07-27 09:27
Looks like all you have to do is
1. Create a specific issue in this github project (like this exact issue, but with more details on your specific need with Premiere CC)
2. Go to Bounty Source, paste the new github issue link into the left side form with the title "Post" and hit the Post button
Thats all?

**Comment by albino1** [comment] 2015-07-27 18:32
I think you need to show some sort of method of replicating the bug and such.  Is the issue simply "doesn't work in CC"?  Or is it something larger and more specific?

For example, in the past I was able to get Frame Server to work the first time I tried to export, but then the next time Adobe Media Encoder would fail to launch and you'd have to go around deleting files to get AME back.  I'm not sure how to replicate that consistently, or explain what's happening.  I don't even remember how I finally managed to fix it :)

I think this ported messy GoogleCodeExporter discussion kind of talks about it:

https://github.com/satishsampath/frame-server/issues/25

So, is the issue now something longer and more complicated, such as "Debugmode Frame Server exports on first try, but then corrupts AME, causing it to be unable to open"?  Something like that maybe?

**Comment by satishsampath** [comment] 2015-07-28 08:38
Yes, if you have consistent reproduction steps that'd be ideal. Otherwise create a github issue like "Improve stability of Frameserver with Premiere CC" and list all the items in that issue?

**Comment by albino1** [comment] 2015-07-28 23:21
Great, I went ahead and created one.  We'll see what happens :)  Thanks Satish!

**Comment by satishsampath** [comment] 2015-07-29 04:42
Thank you @albino1 . Lets close this issue if you are ok with it.

**Closed by satishsampath** 2015-07-29 04:42 UTC

**Comment by malini-cumincode** [comment] 2021-10-02 17:28
CuminCode (the new developers of FrameServer) have built a paid version at https://www.cumincode.com/frameserver/ . If you'd like to support the project, please feel free to contact for feature requests or purchasing a license.
