### ISSUE TITLE
Not working with recent ffmpeg

### ISSUE THREAD

**Issue by hclivess** [satishsampath/frame-server#50] opened 2019-07-20 22:18 UTC
I ran into an issue when trying to run frame-server with ffmpeg-20190713-f86f213-win64-static, but the error was reported by AviSynth, so I am not sure where is the problem. "Avisynth: Unknown Error" was reported. Close if irrelevant.

**Comment by satishsampath** [comment] 2019-08-03 22:13
Can you please give me the steps or share a video of your workflow, showing the issue happening? That will help me install the same software, follow the same steps and try out. For example, see the videos shared in issue #48

**Comment by satishsampath** [comment] 2019-09-07 15:27
Closing as I can't reproduce. If you encounter this again, please reopen the issue and add steps or a video showing how it happens.

**Closed by satishsampath** 2019-09-07 15:27 UTC
